# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-15 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='title',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
