# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-08 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checklist',
            unique_together=set([('task_description', 'is_completed')]),
        ),
    ]
