# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-08 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_auto_20171008_2209'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checklist',
            unique_together=set([('tasks', 'is_completed')]),
        ),
    ]
