# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-15 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_auto_20171015_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='tags',
        ),
    ]
