# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-08 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_auto_20171008_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkcontent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkbox', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Checktext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=60, null=True, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='checklist',
            options={},
        ),
        migrations.AddField(
            model_name='checklist',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='checklist',
            unique_together=set([]),
        ),
        migrations.AddField(
            model_name='checkcontent',
            name='Checklist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='checklist.Checklist'),
        ),
        migrations.AddField(
            model_name='checkcontent',
            name='check_text',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='checklist.Checktext', to_field='text'),
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='task_description',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='tasks',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
