# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-15 19:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_remove_checklist_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='created_date',
            field=models.DateField(default=datetime.date(2017, 10, 16)),
        ),
        migrations.AddField(
            model_name='checklist',
            name='reminder_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Work-Office', 'Work/Office'), ('Home', 'Home'), ('School-College', 'School/College'), ('Hobby', 'Hobby'), ('Others', 'Others')], max_length=44, null=True),
        ),
    ]
