# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-08 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_auto_20171008_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkcontent',
            old_name='Checklist',
            new_name='checklist',
        ),
    ]
