# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-16 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_auto_20171016_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
