# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-08 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_auto_20171008_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todotask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.BooleanField(default=False)),
                ('checklist', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='checklist.Checklist')),
            ],
        ),
        migrations.CreateModel(
            name='Todotext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=120, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='checkcontent',
            name='check_text',
        ),
        migrations.RemoveField(
            model_name='checkcontent',
            name='checklist',
        ),
        migrations.DeleteModel(
            name='Checkcontent',
        ),
        migrations.DeleteModel(
            name='Checktext',
        ),
        migrations.AddField(
            model_name='todotask',
            name='task_text',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='checklist.Todotext', to_field='text'),
        ),
    ]
