# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-16 12:35
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_checklist_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Wk/Of', 'Wk/Of'), ('Hm', 'Hm'), ('Sc/Co', 'Sc/Co'), ('Ho', 'Ho'), ('Ot', 'Ot')], max_length=20, null=True),
        ),
    ]
