# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-16 13:52
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0006_auto_20171016_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Wk/Of', 'Work/Office'), ('Hm', 'Home'), ('Sc/Co', 'School/College'), ('Ho', 'Hobby'), ('Ot', 'Others')], max_length=20, null=True),
        ),
    ]
