# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-16 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0008_auto_20171016_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customtags',
            old_name='checklist',
            new_name='usertag',
        ),
    ]
