# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0009_auto_20171016_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtags',
            name='usertag',
        ),
        migrations.AddField(
            model_name='customtags',
            name='checklist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='custom_tags', to='checklist.Checklist'),
        ),
    ]
