# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 10:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0010_auto_20171016_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='created_date',
            field=models.DateField(default=datetime.date(2017, 10, 18)),
        ),
    ]
