# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0011_auto_20171018_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtags',
            name='checklist',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_tags', to='checklist.Checklist'),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='checklist',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='checklist.Checklist'),
        ),
    ]
