# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-15 09:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('created_date', models.DateField(default=datetime.date(2017, 9, 15))),
                ('reminder_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
