# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-15 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0002_notes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='reminder_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
