# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-15 17:24
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0003_auto_20170915_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('work', 'Work/Office'), ('home', 'Home'), ('school-college', 'School/College'), ('hobby', 'Hobby'), ('others', 'Others')], max_length=37, null=True),
        ),
    ]
