# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-15 22:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0005_auto_20170915_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='created_date',
            field=models.DateField(default=datetime.date(2017, 9, 16)),
        ),
    ]
