# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-03 15:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0006_auto_20170916_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='created_date',
            field=models.DateField(default=datetime.date(2017, 10, 3)),
        ),
        migrations.AlterField(
            model_name='notes',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Work-Office', 'Work/Office'), ('Home', 'Home'), ('School-College', 'School/College'), ('Hobby', 'Hobby'), ('Others', 'Others')], max_length=44, null=True),
        ),
    ]
