# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-15 11:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0010_auto_20171008_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='created_date',
            field=models.DateField(default=datetime.date(2017, 10, 15)),
        ),
    ]
